parameters:
    wallabag_user.twofactor.email.provider.class: Wallabag\UserBundle\Security\TwoFactor\Email\Helper
    wallabag_user.twofactor.email.interactive_login_listener.class: Wallabag\UserBundle\Security\TwoFactor\Email\InteractiveLoginListener
    wallabag_user.twofactor.email.request_listener.class: Wallabag\UserBundle\Security\TwoFactor\Email\RequestListener

services:
    wallabag_user.twofactor.email.provider:
        class: %wallabag_user.twofactor.email.provider.class%
        arguments: ['@doctrine.orm.entity_manager', '@mailer']
    wallabag_user.twofactor.email.interactive_login_listener:
        class: %wallabag_user.twofactor.email.interactive_login_listener.class%
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
        arguments: ['@wallabag_user.twofactor.email.provider']
    wallabag_user.twofactor.email.request_listener:
        class: %wallabag_user.twofactor.email.request_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }
        arguments: ['@wallabag_user.twofactor.email.provider', '@security.context', '@templating', '@router']
