language: php

# use docker-container infra
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - v2

before_script:
  - composer self-update

script:
  - ant prepare
  - phpunit --coverage-text
