imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    # to be able to read emails sent
    spool:
        type: file

doctrine:
    dbal:
        driver: pdo_sqlite
        path: %kernel.root_dir%/../data/db/wallabag_test.sqlite
        host: localhost
    orm:
        metadata_cache_driver:
            type: service
            id: filesystem_cache
        query_cache_driver:
            type: service
            id: filesystem_cache
