app:
    resource: @WallabagCoreBundle/Controller/
    type:     annotation

homepage:
    pattern:   /
    defaults:  { _controller: WallabagCoreBundle:Entry:showUnread }

doc-api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

#wallabag_api:
#    resource: "@WallabagApiBundle/Controller/"
#    type:     annotation
#    prefix:   /api

rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api