services:
    wallabag_import.pocket.import:
        class: Wallabag\ImportBundle\Import\PocketImport
        arguments:
            - "@security.token_storage"
            - "@session"
            - "@doctrine.orm.entity_manager"
            - %pocket_consumer_key%
