services:
    wallabag_import.pocket.client:
        class: GuzzleHttp\Client
        arguments:
            -
                defaults:
                    headers:
                        content-type: "application/json"
                        X-Accept: "application/json"

    wallabag_import.pocket.import:
        class: Wallabag\ImportBundle\Import\PocketImport
        arguments:
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
            - %pocket_consumer_key%
        calls:
            - [ setClient, [ "@wallabag_import.pocket.client" ] ]
            - [ setLogger, [ "@logger" ]]
